# Generated by Django 3.2.6 on 2021-11-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpac_sisac', models.CharField(blank=True, max_length=10, null=True)),
                ('id_paciente_mosaiq', models.CharField(max_length=10)),
                ('cpf', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
