# Generated by Django 3.2.6 on 2021-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
    ]
