version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    command: >
      sh -c "
             redis-server --daemonize yes &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"  
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment: 
      - DB_POSTGRES_HOST=db
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_MOSAIQ_NAME=${DB_MOSAIQ_NAME}
      - DB_MOSAIQ_USER=${DB_MOSAIQ_USER}
      - DB_MOSAIQ_PASSWORD=${DB_MOSAIQ_PASSWORD}
      - DB_MOSAIQ_HOST=${DB_MOSAIQ_HOST}
      - DB_MOSAIQ_PORT=${DB_MOSAIQ_PORT}
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine 
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres     
