# Generated by Django 3.2.6 on 2021-11-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaiq_app', '0002_dose_hst_fase_patcplan_txfield_txfieldpoint'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='vw_PatBro_Demographics',
        ),
    ]
