# Generated by Django 3.2.6 on 2021-10-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('codpaciente', models.CharField(blank=True, db_column='CodPaciente', max_length=10, null=True)),
                ('codmovimento', models.CharField(db_column='CodMovimento', max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=25, null=True)),
                ('fechado', models.CharField(blank=True, db_column='Fechado', max_length=20, null=True)),
                ('datahoraent', models.DateTimeField(blank=True, db_column='DataHoraEnt', null=True)),
                ('codconvenio', models.CharField(blank=True, db_column='CodConvenio', max_length=6, null=True)),
                ('codmedico', models.CharField(blank=True, db_column='CodMedico', max_length=6, null=True)),
                ('hist', models.CharField(blank=True, db_column='Hist', max_length=200, null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'Entrada',
                'managed': False,
            },
        ),
    ]
