# Generated by Django 3.2.6 on 2021-10-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entradaradio_planejfisico_radioterapia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejfisicoc',
            fields=[
                ('idplanejfisicoc', models.CharField(db_column='idPlanejFisicoC', max_length=10, primary_key=True, serialize=False)),
                ('energia', models.CharField(blank=True, db_column='Energia', max_length=50, null=True)),
                ('dtt', models.CharField(blank=True, db_column='DTT', max_length=50, null=True)),
                ('dtd', models.CharField(blank=True, db_column='DTD', max_length=100, null=True)),
                ('naplicacoes', models.IntegerField(blank=True, db_column='NAplicacoes', null=True)),
                ('dosemonitor', models.CharField(blank=True, db_column='DoseMonitor', max_length=100, null=True)),
                ('datasist', models.DateTimeField(db_column='DataSist')),
                ('ativo', models.CharField(db_column='Ativo', max_length=5)),
                ('nplanejamento', models.IntegerField(blank=True, db_column='NPlanejamento', null=True)),
                ('ntratamento', models.IntegerField(blank=True, db_column='NTratamento', null=True)),
                ('locanatomica', models.CharField(db_column='LocAnatomica', max_length=250)),
                ('ncampo', models.IntegerField(blank=True, db_column='NCampo', null=True)),
                ('iniciotrat', models.IntegerField(blank=True, db_column='InicioTrat', null=True)),
                ('fase', models.IntegerField(blank=True, db_column='Fase', null=True)),
            ],
            options={
                'db_table': 'PlanejFisicoC',
                'managed': False,
            },
        ),
    ]
