# Generated by Django 3.2.6 on 2021-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEntrada',
            fields=[
                ('codpaciente', models.CharField(blank=True, db_column='CodPaciente', max_length=10, null=True)),
                ('paciente', models.CharField(blank=True, db_column='Paciente', max_length=200, null=True)),
                ('codmovimento', models.CharField(db_column='CodMovimento', max_length=10, primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, db_column='Matricula', max_length=30, null=True)),
                ('tipoatd', models.CharField(blank=True, db_column='TipoAtd', max_length=25, null=True)),
                ('situacao', models.CharField(blank=True, db_column='Situacao', max_length=20, null=True)),
                ('datahoraent', models.DateTimeField(blank=True, db_column='DataHoraEnt', null=True)),
                ('datahorasai', models.DateTimeField(blank=True, db_column='DataHoraSai', null=True)),
                ('codconvenio', models.CharField(blank=True, db_column='CodConvenio', max_length=6, null=True)),
                ('convenio', models.CharField(blank=True, db_column='Convenio', max_length=100, null=True)),
                ('plano', models.CharField(blank=True, db_column='Plano', max_length=100, null=True)),
                ('codmedico', models.CharField(blank=True, db_column='CodMedico', max_length=6, null=True)),
                ('medico', models.CharField(blank=True, db_column='Medico', max_length=200, null=True)),
                ('codamb', models.CharField(blank=True, db_column='CodAmb', max_length=20, null=True)),
                ('procedimento', models.CharField(blank=True, db_column='Procedimento', max_length=500, null=True)),
                ('hist', models.CharField(blank=True, db_column='Hist', max_length=200, null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'API_Entrada',
                'managed': False,
            },
        ),
    ]
