# Generated by Django 3.2.6 on 2021-10-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_planejfisicoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescrRadio',
            fields=[
                ('idprescrradio', models.AutoField(db_column='idPrescrRadio', primary_key=True, serialize=False)),
                ('idradio', models.IntegerField(db_column='idRadio')),
                ('ncampos', models.IntegerField(db_column='NCampos')),
                ('codmovimento', models.CharField(db_column='CodMovimento', max_length=11)),
                ('locanatomica', models.CharField(db_column='LocAnatomica', max_length=100)),
                ('prof', models.CharField(db_column='Prof', default='', max_length=5)),
                ('datasist', models.DateTimeField(db_column='DataSist')),
                ('grupoemp', models.CharField(db_column='GrupoEmp', default='01', max_length=2)),
                ('filial', models.CharField(db_column='Filial', default='01', max_length=2)),
                ('incidencia', models.CharField(db_column='Incidencia', max_length=20)),
                ('naplicacoes', models.IntegerField(db_column='NAplicacoes')),
                ('portal', models.IntegerField(db_column='Portal', default=5)),
                ('ntratamento', models.IntegerField(db_column='NTratamento')),
                ('tratado', models.CharField(db_column='Tratado', default='NAO', max_length=3)),
                ('iniciotrat', models.IntegerField(db_column='InicioTrat')),
                ('nrestudo', models.IntegerField(db_column='NReestudo', default=0)),
                ('usuario', models.CharField(db_column='Usuario', default='API', max_length=100)),
                ('energia', models.CharField(db_column='Energia', max_length=7)),
                ('tecnica', models.CharField(db_column='Tecnica', max_length=20)),
                ('tpfeixe', models.CharField(db_column='TpFeixe', max_length=20)),
                ('dosettotal', models.IntegerField(db_column='DoseTTotal')),
                ('dosetdiaria', models.IntegerField(db_column='DoseTDiaria')),
                ('fase', models.IntegerField(db_column='Fase')),
            ],
            options={
                'db_table': 'PrescrRadio',
                'managed': False,
            },
        ),
    ]
