# Generated by Django 3.2.6 on 2021-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apiconsulta_apienfevoluc_apientradaradio_apiplanejfisicoc_apiprescreve_apiprescreveqt_apiradioterapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAplicMM_PrescEletiva',
            fields=[
                ('idaplic', models.IntegerField(db_column='IDAplic', primary_key=True, serialize=False)),
                ('ndoc', models.CharField(blank=True, db_column='NDoc', max_length=11, null=True)),
                ('npresc', models.CharField(blank=True, db_column='NPresc', max_length=11, null=True)),
                ('grupop', models.CharField(blank=True, db_column='GrupoP', max_length=200, null=True)),
                ('codpaciente', models.CharField(blank=True, db_column='CodPaciente', max_length=12, null=True)),
                ('paciente', models.CharField(blank=True, db_column='Paciente', max_length=200, null=True)),
                ('hora', models.CharField(blank=True, db_column='Hora', max_length=5, null=True)),
                ('codproduto', models.CharField(blank=True, db_column='CodProduto', max_length=10, null=True)),
                ('descr', models.CharField(blank=True, db_column='Descr', max_length=150, null=True)),
                ('un', models.CharField(blank=True, db_column='Un', max_length=10, null=True)),
                ('quant', models.DecimalField(blank=True, db_column='Quant', decimal_places=2, max_digits=5, null=True)),
                ('codenf', models.CharField(blank=True, db_column='CodEnf', max_length=10, null=True)),
                ('enfermeiro', models.CharField(blank=True, db_column='Enfermeiro', max_length=200, null=True)),
                ('datahora', models.DateTimeField(blank=True, db_column='DataHora', null=True)),
                ('aplicado', models.CharField(blank=True, db_column='Aplicado', max_length=10, null=True)),
            ],
            options={
                'db_table': 'API_AplicMM_PrescEletiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiAplicMM_PrescQT',
            fields=[
                ('idaplic', models.IntegerField(db_column='IDAplic', primary_key=True, serialize=False)),
                ('ndoc', models.CharField(blank=True, db_column='NDoc', max_length=11, null=True)),
                ('npresc', models.CharField(blank=True, db_column='NPresc', max_length=11, null=True)),
                ('codpaciente', models.CharField(blank=True, db_column='CodPaciente', max_length=12, null=True)),
                ('paciente', models.CharField(blank=True, db_column='Paciente', max_length=200, null=True)),
                ('hora', models.CharField(blank=True, db_column='Hora', max_length=5, null=True)),
                ('codproduto', models.CharField(blank=True, db_column='CodProduto', max_length=10, null=True)),
                ('descr', models.CharField(blank=True, db_column='Descr', max_length=150, null=True)),
                ('un', models.CharField(blank=True, db_column='Un', max_length=10, null=True)),
                ('quant', models.DecimalField(blank=True, db_column='Quant', decimal_places=2, max_digits=5, null=True)),
                ('codenf', models.CharField(blank=True, db_column='CodEnf', max_length=10, null=True)),
                ('enfermeiro', models.CharField(blank=True, db_column='Enfermeiro', max_length=200, null=True)),
                ('datahora', models.DateTimeField(blank=True, db_column='DataHora', null=True)),
                ('aplicado', models.CharField(blank=True, db_column='Aplicado', max_length=10, null=True)),
                ('grupop', models.CharField(blank=True, db_column='GrupoP', max_length=200, null=True)),
                ('diaquimioterapia', models.CharField(blank=True, db_column='DiaQuimioterapia', max_length=10, null=True)),
            ],
            options={
                'db_table': 'API_AplicMM_PrescQT',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
