# Generated by Django 3.2.6 on 2021-10-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prescrradio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadConvenio',
            fields=[
                ('codconvenio', models.CharField(db_column='CodConvenio', max_length=5, primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='Descr', max_length=100)),
            ],
            options={
                'db_table': 'CadConvenio',
                'managed': False,
            },
        ),
    ]
