# Generated by Django 3.2.6 on 2021-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_exame_fatura_solicexa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabAmb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codamb', models.CharField(db_column='CodAmb', max_length=10)),
                ('descr', models.CharField(db_column='Descr', max_length=800)),
                ('ch', models.IntegerField(db_column='CH')),
                ('chanest', models.IntegerField(db_column='CHAnest')),
            ],
            options={
                'db_table': 'TabAmb',
                'managed': False,
            },
        ),
    ]
