# Generated by Django 3.2.6 on 2021-11-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
